# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15j-ACP7W1sA5sYKmA4CdQZcWVxqNMIpK
"""

import pandas as pd
import numpy as np

ds= pd.read_csv('/content/healthcare-dataset-stroke-data.csv')

ds.head(10)

ds.info()

ds.tail()

ds.describe()

ds.iloc[:,-2:]

ds.loc[1:10,['id','heart_disease','bmi']]

senior_citizen= ds[ds['age']>=50]

senior_citizen.head(10)

senior_citizen[['id','gender','Residence_type','heart_disease']]

senior_citizen.shape

ds.head()

ds.set_index('id', inplace=True)

ds.head()

print(f"The maximum glucose level is {ds['avg_glucose_level'].max()}")

print(f"bmi below 20 : {ds[ds['bmi']<20]}")

